# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.18.073419'

RELEASE_GIT_HEAD = '3659fe1cbb081d10fb993b70f500c5880c032b6d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jtduan/yt-dlp-custom'

ORIGIN = 'jtduan/yt-dlp-custom'

_pkg_version = '2025.04.18.073419'
