# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.18.065926'

RELEASE_GIT_HEAD = '8e2243548969f44f1d0ff35022f1a11dfcc1d29d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jtduan/yt-dlp-custom'

ORIGIN = 'jtduan/yt-dlp-custom'

_pkg_version = '2025.04.18.065926'
