# Autogenerated by devscripts/update-version.py

__version__ = '2025.04.18.083622'

RELEASE_GIT_HEAD = '3c374b1d1fefe309d481f0c86b9fd5330681629a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'jtduan/yt-dlp-custom'

ORIGIN = 'jtduan/yt-dlp-custom'

_pkg_version = '2025.04.18.083622'
